---
# Roles and Collections for Maschin Playbook
# Date: 03.10.2020

roles:
  - name: arillso.authorized_key
    src: arillso.authorized_key
    version: 1.0.0
  - name: arillso.chocolatey
    src: arillso.chocolatey
    version: 1.3.3
  - name: arillso.sshd
    src: arillso.sshd
    version: 2.2.1

collections:
  - name: sbaerlocher.virtualization
    version: 0.0.9
  - name: sbaerlocher.windows
    version: 0.0.7
