---
# Roles and Collections for Maschin Playbook
# Date: 11.09.2020

roles:
  - name: arillso.authorized_key
    src: arillso.authorized_key
    version: 1.0.0
  - name: arillso.chocolatey
    src: arillso.chocolatey
    version: 1.3.3
  - name: arillso.sshd
    src: arillso.sshd
    version: 2.2.0

collections:
  - name: sbaerlocher.virtualization
    version: 0.0.4
  - name: sbaerlocher.windows
    version: 0.0.6
